[package]
name = "rmrk"
version = "0.5.0"
authors = ["Stake Technologies <devops@stake.co.jp>"]
edition = "2021"

[dependencies]
ink = { version = "4.0.0", default-features = false } 
scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2.3", default-features = false, features = ["derive"], optional = true }
openbrush = { tag = "3.0.0", git = "https://github.com/727-Ventures/openbrush-contracts", default-features = false, features = ["access_control", "reentrancy_guard", "psp34"] }

rmrk_base = { path = "../base", default-features = false, optional = true }
rmrk_minting = { path = "../minting", default-features = false, optional = true }
rmrk_multiasset = { path = "../multiasset", default-features = false, optional = true }
rmrk_nesting = { path = "../nesting", default-features = false, optional = true }
rmrk_common = { path = "../common", default-features = false, optional = true }
rmrk_equippable = { path = "../equippable", default-features = false, optional = true }

[lib]
path = "src/lib.rs"
crate-type = ["rlib"]

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info",
    "scale-info/std",
    "openbrush/std",
    "rmrk_common/std",
    "rmrk_base/std",
    "rmrk_minting/std",
    "rmrk_multiasset/std",
    "rmrk_nesting/std",
    "rmrk_equippable/std",
]
mintable = [ "rmrk_common", "rmrk_minting" ] 
equippable = ["mintable", "rmrk_base", "rmrk_multiasset", "rmrk_nesting", "rmrk_equippable"]


