name: Test

on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo

    - name: Set-Up
      run: sudo apt install -y git clang curl libssl-dev llvm libudev-dev protobuf-compiler

    - name: Install toolchain
      # hacky way to install rust. Rustup is pre-installed on runners. Calling rustup show will detect the rust-toolchain.toml, and subsequently
      # download the needed toolchain and components.
      run: |
        rustup toolchain install nightly
        rustup component add clippy --toolchain nightly-x86_64-unknown-linux-gnu
        rustup show
    - name: Check
      run: cargo +nightly check

    - name: Test
      run: cargo +nightly test

    - name: Lint
      run: cargo +nightly clippy
